/* dtc-db.js — Base massive DTC (moteur, boîte, ABS, ADAS/FrontAssist, airbag, dépollution, HT, refroidissement) */
(function(){
'use strict';
var D={
/* --- MOTEUR / GESTION --- */
'P0001':['Régulateur débit carburant : circuit','Régulateur, câblage','Contrôle circuit + régulateur'],
'P0002':['Régulateur débit carburant : plage','Régulateur encrassé','Contrôle/remplace régulateur'],
'P0008':['Calage distribution (banc 1)','Chaîne/courroie détendue','Contrôle calage + kit'],
'P0009':['Calage distribution (banc 2)','Chaîne/courroie','Contrôle calage banc 2'],
'P0010':['Actionneur AAC A (b1) circuit','Électrovanne VVT','Contrôle électrovanne'],
'P0011':['AAC A (b1) calage avancé','VVT grippé, huile','Contrôle VVT + huile'],
'P0012':['AAC A (b1) calage retardé','VVT, chaîne','Contrôle VVT + calage'],
'P0013':['Actionneur AAC B (b1) circuit','Électrovanne','Contrôle électrovanne B'],
'P0014':['AAC B (b1) calage avancé','VVT','Contrôle VVT'],
'P0016':['Corrélation vilo/AAC admission','Distribution décalée, capteur, VVT','Contrôle calage, capteurs, phasers'],
'P0017':['Corrélation vilo/AAC échappement','Idem P0016','Idem P0016'],
'P0018':['Corrélation vilo/AAC (b2 adm)','Distribution banc 2','Contrôle calage b2'],
'P0019':['Corrélation vilo/AAC (b2 éch)','Distribution banc 2','Contrôle calage b2'],
'P0020':['Actionneur AAC A (b2) circuit','Électrovanne','Contrôle électrovanne b2'],
'P0030':['Sonde lambda amont : chauffe','Sonde, câblage','Contrôle chauffe sonde'],
'P0031':['Sonde amont chauffe basse','Sonde/câblage','Remplace sonde amont'],
'P0032':['Sonde amont chauffe haute','Sonde/câblage','Contrôle sonde'],
'P0036':['Sonde aval : chauffe','Sonde aval','Contrôle chauffe aval'],
'P0037':['Sonde aval chauffe basse','Sonde aval HS','Remplace sonde aval'],
'P0045':['Électrovanne turbo A circuit','Électrovanne','Contrôle électrovanne turbo'],
'P0046':['Électrovanne turbo A plage','Électrovanne grippée','Nettoie/remplace'],
'P0047':['Électrovanne turbo A basse','Câblage','Contrôle circuit'],
'P0048':['Électrovanne turbo A haute','Électrovanne HS','Remplace'],
'P0069':['Corrélation MAP/pression turbo','Capteurs, fuite','Contrôle capteurs + étanchéité'],
'P0071':['T° ambiante plage','Capteur HS','Remplace capteur'],
'P0072':['T° ambiante basse','Capteur/câblage','Contrôle capteur'],
'P0073':['T° ambiante haute','Capteur/câblage','Contrôle capteur'],
'P0087':['Pression rail basse','Pompe HP, filtre, limaille','Contrôle pression, pompe, rinçage'],
'P0088':['Pression rail haute','Régulateur','Contrôle régulateur'],
'P0089':['Régulateur pression perf','Régulateur HS','Remplace'],
'P0090':['Régulateur pression circuit','Câblage','Contrôle circuit'],
'P0100':['MAF circuit','MAF, câblage','Contrôle MAF'],
'P0101':['MAF plage/perf','MAF encrassé, fuite','Nettoie/remplace MAF'],
'P0102':['MAF basse','MAF/câblage','Contrôle câblage'],
'P0103':['MAF haute','MAF/câblage','Contrôle MAF'],
'P0106':['MAP plage/perf','MAP encrassé','Nettoie/remplace MAP'],
'P0107':['MAP basse','MAP/câblage','Contrôle capteur'],
'P0108':['MAP haute','MAP/câblage','Contrôle capteur'],
'P0111':['T° admission plage','Capteur HS','Remplace capteur'],
'P0112':['T° admission basse','Capteur/câblage','Contrôle capteur'],
'P0113':['T° admission haute','Capteur/câblage','Contrôle capteur'],
'P0116':['T° liquide plage','Sonde, thermostat','Contrôle sonde + thermostat'],
'P0117':['T° liquide basse','Sonde/câblage','Contrôle sonde'],
'P0118':['T° liquide haute','Sonde HS','Remplace sonde'],
'P0121':['Papillon A plage','Papillon encrassé','Nettoie papillon'],
'P0122':['Papillon A basse','Capteur/câblage','Contrôle capteur'],
'P0123':['Papillon A haute','Capteur/câblage','Contrôle capteur'],
'P0125':['T° insuffisante boucle','Thermostat ouvert','Contrôle thermostat'],
'P0128':['Thermostat sous seuil','Thermostat bloqué ouvert','Remplace thermostat'],
'P0131':['Sonde amont basse','Sonde, mélange','Contrôle sonde + mélange'],
'P0132':['Sonde amont haute','Sonde HS','Contrôle sonde'],
'P0133':['Sonde amont lente','Sonde vieillissante','Remplace sonde'],
'P0134':['Sonde amont inactive','Sonde/câblage','Contrôle sonde'],
'P0135':['Sonde amont chauffe HS','Chauffe','Remplace sonde'],
'P0136':['Sonde aval circuit','Sonde aval','Contrôle sonde aval'],
'P0141':['Sonde aval chauffe HS','Chauffe aval','Remplace sonde'],
'P0171':['Mélange pauvre (b1)','Prise air, pompe, sonde','Recherche fuite + sonde'],
'P0172':['Mélange riche (b1)','Injecteur fuyard','Contrôle injecteurs'],
'P0174':['Mélange pauvre (b2)','Prise air b2','Recherche fuite b2'],
'P0175':['Mélange riche (b2)','Injecteurs b2','Contrôle injecteurs b2'],
'P0181':['T° carburant plage','Capteur HS','Remplace capteur'],
'P0191':['Capteur rail plage','Capteur/câblage','Contrôle capteur rail'],
'P0192':['Capteur rail basse','Capteur/câblage','Contrôle capteur'],
'P0193':['Capteur rail haute','Capteur HS','Remplace capteur'],
'P0201':['Injecteur cyl.1 circuit','Injecteur 1','Test injecteur 1'],
'P0202':['Injecteur cyl.2 circuit','Injecteur 2','Test injecteur 2'],
'P0203':['Injecteur cyl.3 circuit','Injecteur 3','Test injecteur 3'],
'P0204':['Injecteur cyl.4 circuit','Injecteur 4','Test injecteur 4'],
'P0217':['Surchauffe moteur','Refroidissement','Arrêter, contrôler circuit'],
'P0222':['Papillon B basse','Capteur/câblage','Contrôle capteur B'],
'P0230':['Pompe carburant circuit','Relais, pompe','Contrôle relais + pompe'],
'P0234':['Turbo surpression','Wastegate','Contrôle wastegate'],
'P0236':['Capteur turbo A plage','Capteur/fuite','Contrôle capteur + durites'],
'P0299':['Pression turbo basse','Fuite, wastegate, turbo, EGR','Contrôle durites/wastegate/turbo'],
'P00AF':['Actuateur turbo HS','Actuateur carbonisé','Remplace actuateur'],
'P0300':['Ratés multiples','Bobines, bougies, injecteurs','Bobines/bougies, compressions'],
'P0301':['Ratés cyl.1','Bobine/bougie 1','Permuter bobine'],
'P0302':['Ratés cyl.2','Bobine/bougie 2','Permuter bobine'],
'P0303':['Ratés cyl.3','Bobine/bougie 3','Permuter bobine'],
'P0304':['Ratés cyl.4','Bobine/bougie 4','Permuter bobine'],
'P0327':['Capteur cliquetis basse','Capteur/câblage','Contrôle capteur'],
'P0328':['Capteur cliquetis haute','Capteur HS','Remplace capteur'],
'P0335':['Capteur vilo circuit','Capteur/câblage','Contrôle capteur vilo'],
'P0336':['Capteur vilo plage','Capteur, cible','Contrôle capteur + cible'],
'P0340':['Capteur AAC A circuit','Capteur, calage','Contrôle capteur + calage'],
'P0341':['Capteur AAC A plage','Capteur HS','Remplace capteur'],
'P0345':['Capteur AAC A (b2)','Capteur/câblage','Contrôle capteur b2'],
'P0351':['Bobine A défaut','Bobine A','Remplace bobine A'],
'P0352':['Bobine B défaut','Bobine B','Remplace bobine B'],
'P0353':['Bobine C défaut','Bobine C','Remplace bobine C'],
'P0354':['Bobine D défaut','Bobine D','Remplace bobine D'],
'P0365':['Capteur AAC B circuit','Capteur/câblage','Contrôle capteur B'],
'P0380':['Préchauffage circuit','Boîtier, bougies','Contrôle boîtier + bougies'],
'P0460':['Jauge carburant circuit','Jauge','Contrôle jauge'],
'P0480':['Ventilateur 1 circuit','Relais, moteur','Contrôle relais + ventilateur'],
'P0522':['Pression huile basse','Capteur/niveau','Contrôle niveau + capteur'],
'P0523':['Pression huile haute','Capteur HS','Remplace capteur'],
'P0560':['Tension système défaut','Batterie, alternateur','Test batterie + charge'],
'P0562':['Tension basse','Batterie/alternateur','Test batterie, masses'],
'P0563':['Tension haute','Régulateur','Contrôle alternateur'],
'P0571':['Contacteur frein A','Contacteur pédale','Remplace contacteur'],
'P0597':['Thermostat chauffe circuit','Thermostat piloté','Contrôle thermostat'],
'P0601':['ECM erreur mémoire','Calculateur','Diagnostic calculateur'],
'P0606':['ECM processeur','Calculateur','Diagnostic calculateur'],
'P0615':['Relais démarreur','Relais','Contrôle relais'],
'P0620':['Commande alternateur','Alternateur','Contrôle alternateur'],
'P0638':['Papillon motorisé plage','Boîtier papillon','Nettoie/remplace boîtier'],
'P0645':['Relais embrayage clim','Relais','Contrôle relais'],
'P0685':['Relais principal ECM','Relais','Contrôle relais'],
'P1199':['Pression rail basse (Ford)','Pompe HP','Contrôle pompe HP'],
'P1336':['Capteur vilo signal','Capteur/câblage','Contrôle capteur'],
'P1602':['Immobiliseur code','Clé/calculateur','Réapprentissage'],
'P2101':['Papillon motorisé circuit','Boîtier','Contrôle boîtier'],
'P2111':['Papillon bloqué ouvert','Boîtier','Nettoie/remplace'],
'P2112':['Papillon bloqué fermé','Boîtier','Nettoie/remplace'],
'P2122':['Pédale D basse','Capteur pédale','Contrôle capteur'],
'P2135':['Corrélation pédale/papillon','Capteurs','Contrôle capteurs'],
'P2177':['Pauvre hors ralenti','Prise air, injecteurs','Recherche fuite'],
'P2187':['Riche au ralenti','Injecteurs','Contrôle injecteurs'],
'P2195':['Sonde bloquée pauvre','Sonde HS','Remplace sonde'],
'P2196':['Sonde bloquée riche','Sonde HS','Remplace sonde'],
'P2227':['Pression barométrique plage','Capteur','Contrôle capteur'],
'P2261':['Soupape décharge turbo','Wastegate','Contrôle wastegate'],
'P2263':['Turbo performance','Turbo/fuite','Contrôle turbo'],
'P2A00':['Sonde amont plage','Sonde','Contrôle sonde'],
'P2A01':['Sonde aval plage','Sonde','Contrôle sonde'],
/* --- DÉPOLLUTION (EGR/FAP/AdBlue/NOx) --- */
'P0401':['EGR débit insuffisant','Vanne encrassée','Nettoie/remplace EGR'],
'P0402':['EGR débit excessif','Vanne bloquée','Nettoie/remplace EGR'],
'P0403':['EGR circuit','Électrovanne','Contrôle circuit EGR'],
'P0404':['EGR plage/perf','Vanne encrassée','Nettoie/remplace'],
'P0405':['EGR capteur A basse','Capteur/câblage','Contrôle capteur'],
'P0406':['EGR capteur A haute','Capteur HS','Remplace capteur'],
'P0420':['Catalyseur efficacité (b1)','Catalyseur, sondes','Contrôle sondes + cata'],
'P0430':['Catalyseur efficacité (b2)','Catalyseur b2','Contrôle cata b2'],
'P0441':['EVAP purge incorrecte','Électrovanne','Remplace électrovanne'],
'P0442':['EVAP petite fuite','Bouchon, durites','Contrôle bouchon'],
'P0443':['EVAP électrovanne circuit','Électrovanne','Contrôle électrovanne'],
'P0451':['EVAP pression plage','Capteur','Contrôle capteur'],
'P0452':['EVAP pression basse','Capteur/câblage','Contrôle capteur'],
'P0453':['EVAP pression haute','Capteur HS','Remplace capteur'],
'P0455':['EVAP grosse fuite','Bouchon, canister','Contrôle bouchon + canister'],
'P0456':['EVAP très petite fuite','Fuite minime','Test fumée'],
'P0496':['EVAP purge élevée','Électrovanne ouverte','Remplace électrovanne'],
'P2002':['FAP efficacité basse','FAP colmaté','Régénération, contrôle FAP'],
'P204D':['AdBlue : qualité/capteur','AdBlue contaminé, capteur','Contrôle qualité AdBlue + capteur'],
'P207F':['AdBlue : qualité réservoir','AdBlue contaminé','Vidange/remplissage AdBlue'],
'P20BA':['AdBlue : chauffe injecteur','Injecteur AdBlue, câblage','Contrôle injecteur AdBlue'],
'P202E':['AdBlue : injection faible','Injecteur bouché, pompe','Contrôle injecteur + pompe AdBlue'],
'P203C':['AdBlue : niveau capteur','Capteur niveau','Contrôle capteur niveau'],
'P20EE':['NOx : efficacité après-traitement','Catalyseur SCR, AdBlue','Contrôle SCR + AdBlue'],
'P2200':['NOx capteur circuit (b1)','Capteur NOx','Contrôle capteur NOx'],
'P2201':['NOx capteur plage (b1)','Capteur NOx','Remplace capteur NOx'],
'P2207':['NOx capteur chauffe (b1)','Capteur NOx','Remplace capteur NOx'],
'P2263':['Dépollution : suralimentation','Turbo/EGR','Contrôle turbo + EGR'],
'P242F':['FAP restriction suie','FAP colmaté','Régénération/remplacement'],
'P2459':['FAP régénérations anormales','Parcours courts','Régénération + capteurs'],
'P2463':['FAP suie excessive','Régénérations incomplètes','Régénération, entretien'],
'P2563':['Turbo position wastegate','Wastegate','Contrôle wastegate'],
/* --- BOÎTE / TRANSMISSION --- */
'P0700':['Calculateur boîte défaut','Mécatronique','Diagnostic boîte, MAJ'],
'P0705':['Gamme boîte A circuit','Capteur/levier','Contrôle capteur gamme'],
'P0706':['Gamme boîte A plage','Capteur','Contrôle capteur'],
'P0710':['T° huile boîte circuit','Capteur','Contrôle capteur T°'],
'P0711':['T° huile boîte élevée','Surchauffe/huile','Refroidissement, vidange'],
'P0715':['Régime entrée boîte','Capteur/mécatronique','Contrôle capteur + mécatro'],
'P0720':['Vitesse sortie boîte','Capteur','Contrôle capteur sortie'],
'P0725':['Régime moteur entrée','Capteur vilo','Contrôle capteur'],
'P0730':['Rapport incorrect','Embrayages, mécatro','Vidange, diagnostic'],
'P0731':['1er rapport incorrect','Embrayage 1','Diagnostic boîte'],
'P0732':['2e rapport incorrect','Embrayage 2','Diagnostic boîte'],
'P0733':['3e rapport incorrect','Embrayage 3','Diagnostic boîte'],
'P0740':['TCC convertisseur circuit','TCC','Diagnostic convertisseur'],
'P0743':['TCC circuit électrique','TCC','Diagnostic convertisseur'],
'P0748':['Électrovanne pression A','Mécatronique','Diagnostic mécatro'],
'P0750':['Électrovanne A','Électrovanne','Diagnostic boîte'],
'P0755':['Électrovanne B','Électrovanne','Diagnostic boîte'],
'P0760':['Électrovanne C','Électrovanne','Diagnostic boîte'],
'P0776':['Électrovanne pression B','Mécatronique DSG/EAT','Vidange + mécatro'],
'P0780':['Défaut de passage','Mécatro/embrayages','Diagnostic boîte'],
'P0841':['Capteur pression boîte A','Mécatronique','Diagnostic mécatro'],
'P0845':['Capteur pression boîte B','Capteur','Contrôle capteur'],
'P0868':['Pression huile boîte basse','Huile/pompe','Vidange + pompe'],
'P0894':['Patinage transmission','Embrayages usés','Diagnostic embrayages'],
'P0900':['Actionneur embrayage A','Actionneur','Contrôle actionneur'],
'P0901':['Actionneur embrayage plage','Actionneur','Contrôle actionneur'],
'P17BF':['Mécatronique DSG (VAG)','Mécatronique DQ200','MAJ + mécatro'],
'P174E':['Mécatronique pression','Mécatronique','Diagnostic mécatro'],
'P2700':['Friction A anormale','Embrayages','Diagnostic boîte'],
'P2714':['Embrayage D bloqué','Embrayage','Diagnostic boîte'],
/* --- ABS / ESP / FREINAGE --- */
'C0035':['Capteur roue AV G','Capteur/câblage','Remplace capteur'],
'C0040':['Capteur roue AV D','Capteur/câblage','Remplace capteur'],
'C0045':['Capteur roue AR G','Capteur/câblage','Remplace capteur'],
'C0050':['Capteur roue AR D','Capteur/câblage','Remplace capteur'],
'C0110':['Moteur pompe ABS','Pompe ABS','Contrôle pompe ABS'],
'C0121':['Relais pompe ABS','Relais','Contrôle relais'],
'C0210':['Capteur AV G signal','Capteur/cible','Contrôle capteur + cible'],
'C0215':['Capteur AV D signal','Capteur/cible','Contrôle capteur'],
'C0221':['Capteur AV G logique','Capteur','Contrôle capteur'],
'C0224':['Capteur AV D logique','Capteur','Contrôle capteur'],
'C0237':['Capteur AR G signal','Capteur','Contrôle capteur'],
'C0240':['Capteur AR D signal','Capteur','Contrôle capteur'],
'C0241':['Capteur AV G circuit','Câblage','Contrôle câblage'],
'C0244':['Capteur AV D circuit','Câblage','Contrôle câblage'],
'C0710':['Direction assistée défaut','Capteur couple','Contrôle direction'],
'C1201':['ABS : contrôle moteur','Moteur/ABS','Diagnostic moteur + ABS'],
'C1236':['ABS : tension basse','Batterie','Test batterie'],
'C1400':['ESP : capteur lacet','Capteur yaw','Calibration capteur lacet'],
'C1425':['ESP : capteur accélération','Capteur','Contrôle capteur'],
/* --- AIRBAG / SRS / CEINTURES --- */
'B0001':['Airbag conducteur circuit','Clockspring, coussin','Diagnostic SRS'],
'B0002':['Airbag passager circuit','Coussin','Diagnostic SRS'],
'B0010':['Airbag latéral G','Coussin latéral','Diagnostic SRS'],
'B0013':['Airbag rideau G','Rideau','Diagnostic SRS'],
'B0020':['Airbag latéral D','Coussin latéral','Diagnostic SRS'],
'B0028':['Airbag rideau D','Rideau','Diagnostic SRS'],
'B0050':['Prétensionneur ceinture G','Prétensionneur','Remplace prétensionneur'],
'B0053':['Prétensionneur ceinture D','Prétensionneur','Remplace prétensionneur'],
'B1000':['Calculateur airbag','Calculateur, clockspring','Diagnostic SRS'],
'B1001':['Calculateur airbag config','Calculateur','Reconfiguration'],
'B1400':['Capteur choc latéral G','Capteur','Contrôle capteur'],
'B1401':['Capteur choc latéral D','Capteur','Contrôle capteur'],
'B1600':['Clockspring circuit','Clockspring','Remplace clockspring'],
'B1610':['Clockspring résistance','Clockspring','Remplace clockspring'],
'B1900':['Airbag : défaut mémoire','Calculateur','Diagnostic SRS'],
/* --- ADAS / FRONT ASSIST / CAMÉRAS --- */
'C1103':['Front Assist : radar AV','Radar sali/décalé','Nettoie/calibre radar'],
'C1104':['Front Assist : radar signal','Radar','Calibration radar'],
'C1287':['Capteur angle volant','Capteur','Calibration capteur angle'],
'C1288':['Capteur angle volant logique','Capteur','Calibration'],
'U0121':['Perte communication ABS','CAN ABS','Contrôle module ABS'],
'U0235':['Perte comm. régulateur AV','Radar/caméra','Contrôle radar + caméra'],
'U0416':['Données ESP invalides','Réseau','Diagnostic réseau'],
'U0417':['Données frein invalides','Réseau','Diagnostic réseau'],
'U0420':['Données direction invalides','Réseau','Diagnostic réseau'],
'U3000':['Module contrôle tension','Alimentation','Contrôle alimentation'],
/* --- CHARGE HT / BATTERIE HT / VE --- */
'P0A0D':['Interlock HT circuit','Câblage orange','Diagnostic HV agréé'],
'P0A0E':['Interlock HT performance','Connecteurs','Diagnostic HV'],
'P0A1F':['Module gestion batterie HT','BMS','Diagnostic BMS'],
'P0A78':['Onduleur puissance','Refroidissement onduleur','Contrôle pompe/liquide'],
'P0A80':['Batterie HT à remplacer','Modules déséquilibrés','Diagnostic modules'],
'P0A93':['Refroidissement onduleur pompe','Pompe HS','Remplace pompe'],
'P0AA6':['Isolement batterie HT','Câbles/pack','Diagnostic HV agréé'],
'P0AFB':['Tension HT basse','Pack/modules','Diagnostic pack'],
'P0B00':['Tension HT capteur A','Capteur','Contrôle capteur'],
'P0B05':['Tension HT capteur A plage','Capteur','Contrôle capteur'],
'P0B10':['Tension cellule module 1','Cellules','Équilibrage modules'],
'P0B15':['Tension cellule module 2','Cellules','Équilibrage'],
'P0B20':['Tension cellule module 3','Cellules','Équilibrage'],
'P0B2A':['Température batterie HT','Capteurs T°','Contrôle capteurs T°'],
'P0B30':['Capteur T° batterie plage','Capteurs','Contrôle capteurs'],
'P0B45':['Contacteur HT principal','Contacteur','Diagnostic contacteur'],
'P0B50':['Contacteur HT circuit','Contacteur','Contrôle contacteur'],
'P0B60':['Relais précharge','Relais','Contrôle relais'],
'P0B75':['Capteur courant HT','Capteur','Contrôle capteur'],
'P0B90':['Isolation HT interne','Pack','Diagnostic pack'],
'P0C73':['DC/DC sortie défaut','DC-DC','Contrôle DC-DC'],
'P0C78':['Convertisseur DC/DC défaillant','DC-DC, charge 12V','Contrôle/remplace DC-DC'],
'P0C79':['DC/DC performance','DC-DC','Contrôle DC-DC'],
'P0D16':['Charge HT : circuit pilote','Câble/borne','Contrôle câble + borne'],
'P0D17':['Charge HT : communication','Câble/borne','Contrôle communication'],
'P1E00':['Défaut charge VE (OBC)','OBC, câble, borne','Contrôle OBC/prise'],
/* --- REFROIDISSEMENT --- */
'P0481':['Ventilateur 2 circuit','Relais, moteur','Contrôle ventilateur 2'],
'P0691':['Ventilateur 1 commande basse','Relais/câblage','Contrôle relais'],
'P0692':['Ventilateur 1 commande haute','Relais','Contrôle relais'],
'P0693':['Ventilateur 2 commande basse','Relais','Contrôle relais'],
'P0694':['Ventilateur 2 commande haute','Relais','Contrôle relais'],
'P2632':['Pompe refroidissement HT','Pompe','Contrôle pompe HT'],
'P2635':['Pompe refroidissement perf','Pompe','Contrôle pompe']
};
function gen(code){var m;
 if(m=code.match(/^P0?3(0[1-9]|1[0-2])$/)){var n=parseInt(m[1],10);return['Ratés cylindre '+n,'Bobine/bougie/injecteur '+n,'Permuter bobine, contrôler'];}
 if(m=code.match(/^P02(0[1-9]|1[0-2])$/)){var c=parseInt(m[1],10);return['Injecteur cyl. '+c,'Injecteur '+c,'Test injecteur '+c];}
 if(m=code.match(/^P03(5[1-8])$/)){var L='ABCDEFGH';var i=parseInt(code.slice(3),10)-51;return['Bobine '+L[i],'Bobine '+L[i],'Remplace bobine '+L[i]];}
 if(m=code.match(/^P06(7[1-9]|80)$/)){var g=parseInt(code.slice(3),10)-70;return['Préchauffage cyl. '+g,'Bougie '+g,'Remplace bougie '+g];}
 return null;}
window.dtcInfo=function(code){code=(code||'').toUpperCase().trim();if(D[code])return D[code];return gen(code);};
window.dtcSuggest=function(q,limit){q=(q||'').toUpperCase().replace(/\s+/g,'');if(!q)return[];var out=[];for(var k in D){if(k.indexOf(q)>-1){out.push({code:k,label:D[k][0]});if(out.length>=limit)break;}}
 if(out.length<limit){for(var c=1;c<=12;c++){var kk='P03'+('0'+c).slice(-2);if(kk.indexOf(q)>-1&&!D[kk]){out.push({code:kk,label:'Ratés cylindre '+c});if(out.length>=limit)break;}}}
 return out;};
window.dtcSystem=function(code){code=(code||'').toUpperCase();
 if(/^P0[0-3]/.test(code)||/^P1[0-3]/.test(code)||/^P2[0-2]/.test(code))return'Moteur';
 if(/^P04|^P2[04]/.test(code))return'Dépollution';
 if(/^P0[7-9]|^P17|^P27/.test(code))return'Boîte';
 if(/^C0[0-2]/.test(code)||/^C1[0-4]/.test(code))return'ABS';
 if(/^B00|^B1[0469]/.test(code))return'Airbag';
 if(/^C11|^C12[89]|^U0[124]/.test(code))return'ADAS';
 if(/^P0[A-F]|^P0[C-D]|^P1E/.test(code))return'HT';
 return'Autre';};
window.DTC_COUNT=Object.keys(D).length;
try{localStorage.setItem('mrt_dtc_local','1');}catch(e){}
})();
